apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-service-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: arch.homework
    http:
      paths:
      - path: /(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: user-service-service
            port:
              number: 80
      - path: /otusapp/[a-z]*/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: user-service-service
            port:
              number: 80